# Generated by Django 6.0.3 on 2026-04-04 23:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="name",
            new_name="full_name",
        ),
        migrations.RenameField(
            model_name="otpverification",
            old_name="verified",
            new_name="is_used",
        ),
        migrations.RemoveField(
            model_name="otpverification",
            name="otp",
        ),
        migrations.AddField(
            model_name="otpverification",
            name="otp_code",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="phone",
            field=models.CharField(
                max_length=13,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone must be in format: +91XXXXXXXXXX",
                        regex="^\\+91\\d{10}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("teacher", "Teacher"),
                    ("admin", "Admin"),
                    ("parent", "Parent"),
                ],
                default="parent",
                max_length=20,
            ),
        ),
        migrations.AlterModelTable(
            name="otpverification",
            table="otp_tokens",
        ),
    ]
