# Generated by Django 6.0.3 on 2026-04-03 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="name",
        ),
        migrations.AddField(
            model_name="student",
            name="class_name",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="student",
            name="full_name",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="student",
            name="parent_name",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="student",
            name="parent_phone",
            field=models.CharField(default="", max_length=15),
        ),
        migrations.AddField(
            model_name="student",
            name="section",
            field=models.CharField(default="", max_length=50),
        ),
    ]
