# Generated by Django 6.0.3 on 2026-04-03 16:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0003_remove_mark_score_remove_mark_total_score_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="announcement",
            old_name="date",
            new_name="date_created",
        ),
        migrations.RenameField(
            model_name="mark",
            old_name="exam_name",
            new_name="exam_type",
        ),
        migrations.RemoveField(
            model_name="attendance",
            name="status",
        ),
        migrations.AddField(
            model_name="attendance",
            name="is_present",
            field=models.BooleanField(default=True),
        ),
        migrations.RemoveField(
            model_name="announcement",
            name="target_parents",
        ),
        migrations.CreateModel(
            name="FeeRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "amount_paid",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("last_payment_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("Pending", "Pending"), ("Paid", "Paid")],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fee_records",
                        to="academy.student",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="FeePayment",
        ),
        migrations.AddField(
            model_name="announcement",
            name="target_parents",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
