# Generated by Django 6.0.3 on 2026-04-04 23:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0004_rename_date_announcement_date_created_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="mark",
            old_name="date",
            new_name="exam_date",
        ),
        migrations.AlterUniqueTogether(
            name="attendance",
            unique_together={("student", "date")},
        ),
        migrations.RemoveField(
            model_name="announcement",
            name="date_created",
        ),
        migrations.RemoveField(
            model_name="announcement",
            name="target_parents",
        ),
        migrations.RemoveField(
            model_name="feerecord",
            name="payment_method",
        ),
        migrations.AddField(
            model_name="announcement",
            name="sender",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="announcements",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="announcement",
            name="target_class",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="attendance",
            name="marked_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="feerecord",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mark",
            name="grade",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("all", "All"),
                    ("parents_only", "Parents Only"),
                    ("specific_class", "Specific Class"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="feerecord",
            name="last_payment_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="feerecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("paid", "Paid"),
                    ("pending", "Pending"),
                    ("partial", "Partial"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="feerecord",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fees",
                to="academy.student",
            ),
        ),
        migrations.AlterField(
            model_name="mark",
            name="marks_obtained",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name="mark",
            name="max_marks",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name="student",
            name="class_name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="student",
            name="full_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="student",
            name="parent_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="student",
            name="parent_phone",
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="section",
            field=models.CharField(max_length=50),
        ),
    ]
