# Generated by Django 6.0.3 on 2026-04-07 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0005_rename_date_mark_exam_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="subjects",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
