# Generated by Django 6.0.3 on 2026-04-07 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0006_student_subjects"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="target_student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="private_announcements",
                to="academy.student",
            ),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("all", "All"),
                    ("parents_only", "Parents Only"),
                    ("specific_class", "Specific Class"),
                    ("specific_student", "Specific Student"),
                ],
                max_length=20,
            ),
        ),
    ]
